apiVersion: v1
kind: Service
metadata:
  name: company-sample-api
  labels:
    run: company-sample-api
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    name: http
  selector:
    run: company-sample-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-sample-api
spec:
  replicas: ${DEPLOY_VARS_replicas}
  selector:
    matchLabels:
      run: company-sample-api
  template:
    metadata:
      labels:
        run: company-sample-api
    spec:
      containers:
      - name: company-sample-api
        image: ${CONTAINER_IMAGE}
        env:
        - name: ENVIRONMENT_NAME
          value: ${ENVIRONMENT_NAME}
        ports:
        - containerPort: 3000